# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exchange' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Exchange
  pod 'AlamofireDomain', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'SnapKit', '~> 4.0.0’
  pod 'SVProgressHUD'

end
